language: android

sudo: false

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27
  licenses:
  - android-sdk-license-.+
before_install:
  - gem install fir-cli
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - openssl aes-256-cbc -K $encrypted_c8b2b093f2df_key -iv $encrypted_c8b2b093f2df_iv -in keys/LX.jks.enc -out keys/LX.jks -d
script:
  - "./gradlew assembleRelease"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
deploy:
  provider: releases
  api_key:
    secure: dOWaBHYQc1lCnpxVoy6ou3MMt/7n+PPl0UAhyxHAbiPVjtIQ4Yr9sATpB9gLPS2lk7FBbCQbnzGlr6Qf6CBpcNhRdMqH1dTxbRTx1KW5Uy4ztt8xXwfpDm5xdBRfxOpttwS6u/BckqnqpRmPYHKPcg57OJyF7RKdcNWF4u47ArTvWFCPtmV8DGmJkd0VVv0KGe9g5hZA5yVIBQbAWqOzU0Cqckjsyx5cpedt6NoTIvtgB4ZLCBghhamZpKSH9gg7sQTu4h6DY6Kwg2snrFY4TP5RRE7Cg4Hb2PeDA8qdNKTYK0TQEZCMuwqG0PKa4tI0VoBenlCTKU9QAOlXXvVo4pO1Nn9AcQSWIxmopS/kBn0S6P9ILb5VU9c0aguRTlsoXr+m6UXTyR+jC4gAs05YMvkSjpCwPQAbYT19EnWzMwkgVmj6trFyRTUYTCHMVYyOlCiLxVWpm63g35e4Q2/7wiHusTfqiSphUVKW3HvHlwZjWTHLZQzLhGljfFDwjBALIbl0L3bXuCuQJARCumRlmTDnE8CToaW7lE6euIrLGvFRQGKZ6vtSgRWV0y/DUBWyd7ajuvoWQIwUT3XMhyYP1VQZ11TeHvMs10GslfoVGFeOuzAEoarUy4ZpytP13X2A3lHSuM0g0KUu96ArCVtjzhCB7j3jz3rN1V5h4gPZQrI=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: taowenyin/RLXAPF
after_deploy:
  - fir publish app/build/outputs/apk/release/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
